language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - nightly

before_script:
  - composer install

script:
  - composer cs
  - composer test

after_script:
  - ./vendor/bin/php-coveralls -v

matrix:
  allow_failures:
    - php: hhvm-3.30
    - php: nightly
