name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        image: [latest, php_7_3, php_7_2]

    name: ${{ matrix.image }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: All
      run: make IMAGE=${{ matrix.image }}
