name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [latest, php_7_3, php_7_2]

    name: ${{ matrix.image }}

    env:
      IMAGE: ${{ matrix.image }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Clean
      run: make clean

    - name: Build
      run: make build

    - name: Install
      run: make install

    - name: Lint
      run: make cs

    - name: Test
      run: make test

  docs:
    runs-on: ubuntu-latest
    name: Generate Documentation

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          pwd
          make docs
          ls -l .
          ls -l build
          ls -l build/docs/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: API.md
          path: ${{ github.workspace }}/build/docs/README.md
