name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build API docs
        run: |
            make docs
            sudo chmod -R 775 build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'changelog here'
          draft: false
          prerelease: false

      - name: Upload API docs
          uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/build/docs/README.md
            asset_name: API.md
            asset_content_type: text/plain
